import type { HelpArticle } from "../types";

export const ACADEMY_ARTICLES: HelpArticle[] = [
  {
    id: "what-seo-is",
    slug: "what-seo-is",
    title: "What SEO is",
    summary: "A plain-language definition of search engine optimization.",
    body: [
      { type: "definition", term: "SEO (Search Engine Optimization)", text: "The practice of improving a website so it's easier for search engines to find, understand, and recommend to people searching for relevant things." },
      { type: "paragraph", text: "SEO touches technical health (can the site be crawled and understood), content (does it answer what people are searching for), and authority (do other trusted sources point to it)." },
      { type: "relatedLink", articleSlug: "why-seo-matters", label: "Why SEO matters" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "academy",
    featureStatus: "available",
    estimatedReadingMinutes: 3,
    tags: ["seo", "academy", "basics"],
    searchAliases: ["what is seo", "define seo"],
    relatedArticleIds: ["why-seo-matters", "business-goals-seo-can-support"],
    relevantRoutes: [],
    priority: "P1",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "why-seo-matters",
    slug: "why-seo-matters",
    title: "Why SEO matters",
    summary: "How search visibility connects to real business outcomes.",
    body: [
      { type: "paragraph", text: "Search is often how people discover a business before they ever hear about it any other way. Better visibility in search tends to mean more qualified visitors finding you at the moment they're looking." },
      { type: "relatedLink", articleSlug: "business-goals-seo-can-support", label: "Business goals SEO can support" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "academy",
    featureStatus: "available",
    estimatedReadingMinutes: 3,
    tags: ["seo", "academy", "why it matters"],
    searchAliases: ["why does seo matter", "importance of seo"],
    relatedArticleIds: ["what-seo-is", "business-goals-seo-can-support"],
    relevantRoutes: [],
    priority: "P1",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "business-goals-seo-can-support",
    slug: "business-goals-seo-can-support",
    title: "Business goals SEO can support",
    summary: "Mapping common business goals to SEO levers.",
    body: [
      { type: "list", items: [
        "More qualified leads or inquiries",
        "Stronger local visibility for a physical business",
        "Brand awareness and credibility",
        "Reduced reliance on paid advertising over time",
      ] },
      { type: "paragraph", text: "Different goals call for different priorities — technical fixes, content, authority building, or a mix." },
      { type: "relatedLink", articleSlug: "what-seo-is", label: "What SEO is" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "academy",
    featureStatus: "available",
    estimatedReadingMinutes: 3,
    tags: ["seo", "academy", "business goals"],
    searchAliases: ["what can seo do for my business", "seo business goals"],
    relatedArticleIds: ["what-seo-is", "why-seo-matters"],
    relevantRoutes: [],
    priority: "P1",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "what-aeo-is",
    slug: "what-aeo-is",
    title: "What AEO is",
    summary: "A plain-language introduction to answer-engine optimization.",
    body: [
      { type: "definition", term: "AEO (Answer Engine Optimization)", text: "Structuring and writing content so it can be directly used as an answer by systems that respond to questions, rather than only listing links." },
      { type: "warning", text: "This is a general educational overview, not a description of any specific engine's proprietary ranking or answer-selection rules." },
      { type: "relatedLink", articleSlug: "what-geo-is", label: "What GEO is" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "intermediate",
    productArea: "academy",
    featureStatus: "available",
    estimatedReadingMinutes: 3,
    tags: ["aeo", "academy", "answer engine"],
    searchAliases: ["what is aeo", "answer engine optimization", "answer engine", "what is answer engine optimization"],
    relatedArticleIds: ["what-geo-is", "how-seo-aeo-geo-work-together"],
    relevantRoutes: [],
    priority: "P1",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
    externalReviewRequired: true,
  },
  {
    id: "what-geo-is",
    slug: "what-geo-is",
    title: "What GEO is",
    summary: "A plain-language introduction to generative-engine optimization.",
    body: [
      { type: "definition", term: "GEO (Generative Engine Optimization)", text: "Making content easier for generative AI systems to find, understand, cite, and summarize accurately when producing AI-generated answers." },
      { type: "warning", text: "This is a general educational overview, not a description of any specific AI system's proprietary ranking or citation rules." },
      { type: "relatedLink", articleSlug: "what-aeo-is", label: "What AEO is" },
      { type: "relatedLink", articleSlug: "ai-visibility-data-is-seeded", label: "AI Visibility data is seeded" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "intermediate",
    productArea: "academy",
    featureStatus: "available",
    estimatedReadingMinutes: 3,
    tags: ["geo", "academy", "generative engine", "ai search"],
    searchAliases: ["what is geo", "generative engine optimization", "ai search", "generative search", "genrative engine optimisation", "generative engine optimisation"],
    relatedArticleIds: ["what-aeo-is", "how-seo-aeo-geo-work-together"],
    relevantRoutes: [],
    priority: "P1",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
    externalReviewRequired: true,
  },
  {
    id: "how-seo-aeo-geo-work-together",
    slug: "how-seo-aeo-geo-work-together",
    title: "How SEO, AEO, and GEO work together",
    summary: "Why these are complementary disciplines built on shared foundations, not separate silos.",
    body: [
      { type: "paragraph", text: "SEO, AEO, and GEO share the same underlying foundation: structured, trustworthy, genuinely useful content that clearly answers real questions. Technical health and credible authority support visibility across all three." },
      { type: "warning", text: "This is a general educational overview and does not claim to describe any specific search or AI system's internal ranking logic." },
      { type: "relatedLink", articleSlug: "what-aeo-is", label: "What AEO is" },
      { type: "relatedLink", articleSlug: "what-geo-is", label: "What GEO is" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "intermediate",
    productArea: "academy",
    featureStatus: "available",
    estimatedReadingMinutes: 4,
    tags: ["seo", "aeo", "geo", "academy"],
    searchAliases: ["seo vs aeo vs geo", "how do these differ", "seo aeo geo overlap"],
    relatedArticleIds: ["what-aeo-is", "what-geo-is"],
    relevantRoutes: [],
    priority: "P1",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
    externalReviewRequired: true,
  },
  {
    id: "technical-content-authority-measurement",
    slug: "technical-content-authority-measurement",
    title: "Technical SEO, content, authority, and measurement",
    summary: "The four pillars of an SEO program, in plain language.",
    body: [
      { type: "list", items: [
        "Technical SEO — can search engines crawl, read, and index your site correctly?",
        "Content — does your site clearly and usefully answer what people search for?",
        "Authority — do other trusted sources point to and vouch for your site?",
        "Measurement — are you tracking what's working so you can iterate?",
      ] },
      { type: "relatedLink", articleSlug: "how-digibility-connects-insights-actions-approvals-reporting", label: "How Digibility connects it all" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "intermediate",
    productArea: "academy",
    featureStatus: "available",
    estimatedReadingMinutes: 4,
    tags: ["seo", "academy", "technical seo", "content", "authority", "measurement"],
    searchAliases: ["seo pillars", "seo fundamentals"],
    relatedArticleIds: ["how-digibility-connects-insights-actions-approvals-reporting"],
    relevantRoutes: [],
    priority: "P1",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "how-digibility-connects-insights-actions-approvals-reporting",
    slug: "how-digibility-connects-insights-actions-approvals-reporting",
    title: "How Digibility connects insights, actions, approvals, and reporting",
    summary: "The operating-system view of Digibility SEO Intelligence.",
    body: [
      { type: "paragraph", text: "Digibility is designed to connect technical health, content, page performance, decline diagnosis, off-page authority, and AI-visibility planning into one website-centric workflow — with role-based collaboration, client visibility, and an append-only history connecting insights to the actions taken on them." },
      { type: "relatedLink", articleSlug: "why-fragmented-seo-workflows-create-problems", label: "Why fragmented SEO workflows create problems" },
      { type: "relatedLink", articleSlug: "how-digibility-complements-teams-freelancers-agencies", label: "How Digibility complements your team" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "academy",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["digibility", "academy", "positioning"],
    searchAliases: ["how does digibility tie this together", "digibility operating system"],
    relatedArticleIds: ["why-fragmented-seo-workflows-create-problems", "how-digibility-complements-teams-freelancers-agencies"],
    relevantRoutes: [],
    priority: "P2",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "why-fragmented-seo-workflows-create-problems",
    slug: "why-fragmented-seo-workflows-create-problems",
    title: "Why fragmented SEO workflows create operational problems",
    summary: "The cost of spreading SEO work across disconnected tools and providers.",
    body: [
      { type: "paragraph", text: "When SEO work lives across disconnected tools, spreadsheets, and separate providers, it's easy to lose track of what was decided, who approved it, and what happened next. Reports without a connected execution and approval workflow don't always translate into completed work." },
      { type: "paragraph", text: "Compared with workflows that rely on separate spreadsheets, consultants, and point solutions, centralizing website-centric data, actions, approvals, and history in one place is intended to make SEO work more visible and accountable." },
      { type: "relatedLink", articleSlug: "how-digibility-complements-teams-freelancers-agencies", label: "How Digibility complements your team" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "positioning",
    featureStatus: "available",
    estimatedReadingMinutes: 3,
    tags: ["positioning", "academy", "fragmented workflows"],
    searchAliases: ["why digibility", "scattered spreadsheets", "disconnected tools"],
    relatedArticleIds: ["how-digibility-complements-teams-freelancers-agencies", "how-digibility-connects-insights-actions-approvals-reporting"],
    relevantRoutes: [],
    priority: "P2",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "how-digibility-complements-teams-freelancers-agencies",
    slug: "how-digibility-complements-teams-freelancers-agencies",
    title: "How Digibility can complement an internal team, freelancer, or agency",
    summary: "Digibility is designed to work alongside the people already doing your SEO work, not replace their expertise.",
    body: [
      { type: "paragraph", text: "Freelancers, consultants, and agencies bring expertise, strategy, and hands-on execution. Digibility is designed to be the shared system of record and approval layer that an internal team, freelancer, or agency can all work inside — improving visibility and accountability for everyone involved." },
      { type: "callout", text: "Digibility combines role-based collaboration and client visibility so business owners, internal teams, and outside help can see the same up-to-date picture." },
      { type: "relatedLink", articleSlug: "why-fragmented-seo-workflows-create-problems", label: "Why fragmented SEO workflows create problems" },
      { type: "relatedLink", articleSlug: "roles-and-permissions", label: "Roles and permissions" },
    ],
    category: "learn-seo-aeo-geo",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "positioning",
    featureStatus: "available",
    estimatedReadingMinutes: 3,
    tags: ["positioning", "academy", "agency", "freelancer"],
    searchAliases: ["do I still need an agency", "digibility vs agency", "digibility vs freelancer"],
    relatedArticleIds: ["why-fragmented-seo-workflows-create-problems", "roles-and-permissions"],
    relevantRoutes: [],
    priority: "P2",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
];

/** Not part of the P0/academy corpus lists above but referenced by "What GEO is" — a
 * minimal honesty stub so the related link resolves within Slice 1's scope. */
export const AI_VISIBILITY_STUB_ARTICLE: HelpArticle = {
  id: "ai-visibility-data-is-seeded",
  slug: "ai-visibility-data-is-seeded",
  title: "AI Visibility data is seeded",
  summary: "AI Visibility in Digibility SEO currently shows seeded preview data, not live AI-model intelligence.",
  body: [
    { type: "statusNotice", text: "AI Visibility reads (prompt tracking, mentions, content gaps) are currently seeded demo content, not live model intelligence. Real AI-visibility ingestion is planned but not yet built." },
    { type: "relatedLink", articleSlug: "what-geo-is", label: "What GEO is" },
    { type: "relatedLink", articleSlug: "preview-data-versus-live-data", label: "Preview data versus live data" },
  ],
  category: "feature-availability",
  contentType: "product_status_notice",
  audienceRoles: ["all"],
  level: "beginner",
  productArea: "ai-visibility",
  featureStatus: "demo_data",
  estimatedReadingMinutes: 1,
  tags: ["ai visibility", "geo", "honesty", "seeded"],
  searchAliases: ["is this real ai data", "ai visibility live", "manual_seed"],
  relatedArticleIds: ["what-geo-is", "preview-data-versus-live-data"],
  relevantRoutes: ["/seo/ai-visibility"],
  priority: "P1",
  lastReviewed: "2026-07-19",
  version: "1",
  published: true,
  visibility: "public",
};
