import type { HelpArticle } from "../types";

export const CRAWL_ARTICLES: HelpArticle[] = [
  {
    id: "starting-and-monitoring-a-crawl",
    slug: "starting-and-monitoring-a-crawl",
    title: "Starting and monitoring a crawl",
    summary: "How to start a website crawl, what the confirmation means, and how to watch its progress.",
    body: [
      { type: "paragraph", text: "A crawl reads your website's public pages and feeds the results into your Audit and Page Inventory. Owners, admins, and team members can start a crawl; clients cannot." },
      { type: "warning", text: "Domain ownership must be verified before a website can be crawled. If it isn't, the crawl request is rejected." },
      { type: "steps", items: [
        "Go to the Audit page for your active website.",
        "Choose \"Start crawl.\"",
        "Confirm — only public pages are analyzed, robots.txt rules are respected, and the crawl is bounded.",
        "Watch the status update as the crawl progresses.",
      ] },
      { type: "statusNotice", text: "Only one crawl can be active per website at a time. Starting a second crawl while one is active is not allowed." },
      { type: "relatedLink", articleSlug: "understanding-crawl-statuses", label: "Understanding crawl statuses" },
      { type: "relatedLink", articleSlug: "why-crawl-rejected-ownership-unverified", label: "Why a crawl is rejected" },
    ],
    category: "website-crawling",
    contentType: "how_to",
    audienceRoles: ["owner", "admin", "team_member"],
    level: "beginner",
    productArea: "crawl",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["crawl", "scan", "start crawl"],
    searchAliases: ["how to crawl", "scan site", "site scan", "run crawl"],
    relatedArticleIds: ["understanding-crawl-statuses", "why-crawl-rejected-ownership-unverified", "why-a-crawl-may-remain-queued"],
    relevantRoutes: ["/seo/audit"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "understanding-crawl-statuses",
    slug: "understanding-crawl-statuses",
    title: "Understanding crawl statuses",
    summary: "What each crawl status means, what to do, and when to wait, refresh, or contact support.",
    body: [
      { type: "table", headers: ["Status", "What it means", "What you should do"], rows: [
        ["Queued", "The crawl was recorded and is waiting to be picked up.", "Wait. See \"Why a crawl may remain queued.\""],
        ["Preparing", "A background worker has taken the job.", "Wait."],
        ["Crawling", "Pages are being fetched within a budget.", "Wait; don't start another crawl."],
        ["Waiting to retry", "A transient issue occurred; a retry is scheduled.", "Wait; this is normal."],
        ["Cancelling", "Your cancel request is being acknowledged.", "Wait."],
        ["Completed", "Results were published to your Audit and Page Inventory.", "Review your audit."],
        ["Partially completed", "Some pages finished; partial results were published.", "Review results; consider a later re-crawl."],
        ["Failed", "The crawl could not complete.", "Check status; re-crawl later; contact support if it repeats."],
        ["Cancelled", "You cancelled it.", "Prior published results remain available."],
      ] },
      { type: "callout", text: "Status is always read from the server, refreshed automatically while active, and safe to check again after a page refresh." },
      { type: "relatedLink", articleSlug: "why-a-crawl-may-remain-queued", label: "Why a crawl may remain queued" },
      { type: "relatedLink", articleSlug: "starting-and-monitoring-a-crawl", label: "Starting and monitoring a crawl" },
    ],
    category: "website-crawling",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "crawl",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["crawl", "status", "queued", "running", "failed"],
    searchAliases: ["what does queued mean", "crawl status", "crawel status", "crawling meaning"],
    relatedArticleIds: ["why-a-crawl-may-remain-queued", "starting-and-monitoring-a-crawl", "why-crawl-rejected-ownership-unverified"],
    relevantRoutes: ["/seo/audit"],
    contextualStates: [
      "crawl:queued", "crawl:claimed", "crawl:running", "crawl:retry_wait",
      "crawl:cancellation_requested", "crawl:completed", "crawl:partially_completed",
      "crawl:failed", "crawl:cancelled",
    ],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "why-crawl-rejected-ownership-unverified",
    slug: "why-crawl-rejected-ownership-unverified",
    title: "Why a crawl is rejected when ownership is unverified",
    summary: "What the \"Domain ownership must be verified\" message means and how to fix it.",
    body: [
      { type: "paragraph", text: "A website can only be crawled once its domain ownership is currently verified. If you try to start a crawl before that, the request is rejected with a message explaining that ownership must be verified first." },
      { type: "steps", items: [
        "Open the website's ownership panel.",
        "Complete or re-check domain ownership verification.",
        "Once the status shows \"Verified,\" start the crawl again.",
      ] },
      { type: "troubleshootingNote", text: "This check happens on every crawl request, including retries — it protects against crawling a domain you no longer control." },
      { type: "relatedLink", articleSlug: "verifying-domain-ownership", label: "Verifying domain ownership" },
      { type: "relatedLink", articleSlug: "starting-and-monitoring-a-crawl", label: "Starting and monitoring a crawl" },
    ],
    category: "website-crawling",
    contentType: "troubleshooting",
    audienceRoles: ["owner", "admin", "team_member"],
    level: "beginner",
    productArea: "crawl",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 2,
    tags: ["crawl", "ownership", "rejected"],
    searchAliases: ["cannot start crawl", "can't start crawl", "crawl rejected", "crawl blocked", "verify first"],
    relatedArticleIds: ["verifying-domain-ownership", "understanding-crawl-statuses"],
    relevantRoutes: ["/seo/audit"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "why-a-crawl-may-remain-queued",
    slug: "why-a-crawl-may-remain-queued",
    title: "Why a crawl may remain queued",
    summary: "The background crawl worker is not continuously deployed in this build — here's what that means for you.",
    body: [
      { type: "statusNotice", text: "In this build, the background crawl worker that actually fetches pages is not continuously deployed. A crawl you start is correctly recorded as \"Queued,\" but it will stay queued until an operator manually runs the worker." },
      { type: "paragraph", text: "This is expected behavior today, not a sign that something is broken." },
      { type: "heading", id: "retry-vs-new", text: "A worker retry is not the same as starting a new crawl" },
      { type: "paragraph", text: "A worker retry re-attempts an existing crawl job automatically. Starting a new crawl creates a brand-new job and must pass the same ownership and single-active-job checks. You never need to click anything for a retry." },
      { type: "escalationNote", text: "If you need a real crawl run for testing or evaluation, contact support and reference this article." },
      { type: "relatedLink", articleSlug: "understanding-crawl-statuses", label: "Understanding crawl statuses" },
      { type: "relatedLink", articleSlug: "preview-data-versus-live-data", label: "Preview data versus live data" },
    ],
    category: "website-crawling",
    contentType: "faq",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "crawl",
    featureStatus: "coming_later",
    estimatedReadingMinutes: 2,
    tags: ["crawl", "queued", "worker", "honesty"],
    searchAliases: ["stuck queued", "not crawling", "worker", "never runs", "queued forever"],
    relatedArticleIds: ["understanding-crawl-statuses", "preview-data-versus-live-data"],
    relevantRoutes: ["/seo/audit"],
    contextualStates: ["crawl:queued"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
];
