import type { HelpArticle } from "../types";

export const HONESTY_ARTICLES: HelpArticle[] = [
  {
    id: "preview-data-versus-live-data",
    slug: "preview-data-versus-live-data",
    title: "Preview data versus live data",
    summary: "How to tell which parts of Digibility SEO show real, live results versus demo or preview content.",
    body: [
      { type: "statusNotice", text: "Digibility SEO is currently a test/preview build. Data you see is seeded demo data unless you have just entered it yourself. Real website crawling, Google Search Console / GA4 metrics, backlink data, and AI-model visibility are not yet live." },
      { type: "table", headers: ["Label", "What it means"], rows: [
        ["Available on TEST", "Working and Supabase-backed on the test project, but over seeded demo data — not yet promoted to production."],
        ["Preview", "Reads exist, but reflect hand-seeded demo content, not live intelligence."],
        ["Demo data", "The specific numbers/rows shown are seeded, not from a live source."],
        ["Mock-only", "Runs entirely on a local simulation; nothing is saved."],
        ["Coming later", "Designed but not built yet."],
      ] },
      { type: "paragraph", text: "Look for these labels on pages that show metrics, diagnoses, or AI-related content, and treat the numbers as illustrative rather than authoritative until they're labeled otherwise." },
      { type: "relatedLink", articleSlug: "why-a-crawl-may-remain-queued", label: "Why a crawl may remain queued" },
      { type: "relatedLink", articleSlug: "getting-started-with-digibility-seo", label: "Getting started" },
    ],
    category: "feature-availability",
    contentType: "product_status_notice",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "honesty",
    featureStatus: "demo_data",
    estimatedReadingMinutes: 2,
    tags: ["preview", "demo data", "honesty", "mock"],
    searchAliases: ["is this data real", "is this real", "demo data", "seeded data", "fake data", "test data", "is this real data"],
    relatedArticleIds: ["why-a-crawl-may-remain-queued", "getting-started-with-digibility-seo"],
    relevantRoutes: [],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "troubleshooting-overview",
    slug: "troubleshooting-overview",
    title: "Troubleshooting overview",
    summary: "Where to start when something isn't working as expected.",
    body: [
      { type: "paragraph", text: "Most problems fall into one of a few categories: access/role issues, the active website being set incorrectly, ownership not yet verified, or the crawl worker not currently running (expected in this build)." },
      { type: "steps", items: [
        "Confirm you're signed in and on the right website.",
        "Confirm your role allows the action you're trying to take.",
        "Read the on-screen message carefully — errors are shown verbatim.",
        "Try a refresh.",
        "If it persists, contact support with the safe details described in \"Contacting support safely.\"",
      ] },
      { type: "relatedLink", articleSlug: "contacting-support-safely", label: "Contacting support safely" },
      { type: "relatedLink", articleSlug: "roles-and-permissions", label: "Roles and permissions" },
    ],
    category: "troubleshooting",
    contentType: "troubleshooting",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "troubleshooting",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 2,
    tags: ["troubleshooting", "help", "error"],
    searchAliases: ["something's wrong", "not working", "broken", "error"],
    relatedArticleIds: ["contacting-support-safely", "roles-and-permissions"],
    relevantRoutes: [],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "contacting-support-safely",
    slug: "contacting-support-safely",
    title: "Contacting support safely",
    summary: "What's safe to share with support, and what to never share.",
    body: [
      { type: "warning", text: "Never share your password, any service-role/API key, a DNS verification token/value, or internal diagnostic tokens with support or anyone else." },
      { type: "paragraph", text: "Safe to share: the website/workspace name, the page/route you were on, your role, the status you saw, a timestamp, a screenshot with any secret values hidden, and what you already tried (e.g. refresh, sign out and back in)." },
      { type: "paragraph", text: "Signing in may be required to open a support request. If you're signed out, sign in first and then use Contact Support." },
      { type: "relatedLink", articleSlug: "troubleshooting-overview", label: "Troubleshooting overview" },
    ],
    category: "contact-support",
    contentType: "support_runbook",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "support",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 2,
    tags: ["support", "contact", "escalation"],
    searchAliases: ["how do I contact support", "get help", "contact digibility"],
    relatedArticleIds: ["troubleshooting-overview"],
    relevantRoutes: ["/seo/support"],
    supportEscalationType: "general",
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
];
