import type { HelpArticle } from "../types";

export const OWNERSHIP_ARTICLES: HelpArticle[] = [
  {
    id: "verifying-domain-ownership",
    slug: "verifying-domain-ownership",
    title: "Verifying domain ownership (DNS TXT)",
    summary: "How to prove you control a website's domain using a DNS TXT record, and what each status means.",
    body: [
      { type: "paragraph", text: "Before a website can be crawled, its domain ownership must be verified. This is done by adding a DNS TXT record that proves you control the domain." },
      { type: "heading", id: "how-to-verify", text: "How to verify" },
      { type: "steps", items: [
        "On the Websites page, find the website and open its ownership panel.",
        "Choose \"Verify ownership\" (owner/admin only).",
        "Add the shown DNS TXT record at your domain host: Type = TXT, an exact Host, and an exact Value.",
        "Wait for DNS to propagate — this can take some time.",
        "Choose \"Check again\" once the record is added.",
      ] },
      { type: "warning", text: "Never share the DNS TXT Value with anyone outside your organization, including in a support chat, email, or screenshot. It is a verification secret for your website. Support will never ask you for it." },
      { type: "heading", id: "states", text: "Ownership states" },
      { type: "table", headers: ["Status", "Meaning", "Who can act"], rows: [
        ["Not verified", "Ownership hasn't been verified yet.", "Owner/Admin can start verification."],
        ["Verification pending", "A DNS TXT record was requested; add it and check again.", "Owner/Admin can Check again or Re-verify."],
        ["Verified", "Ownership is confirmed for this host.", "Owner/Admin can Re-verify or Revoke."],
        ["Verification failed", "The DNS record wasn't found or didn't match.", "Owner/Admin can Check again or Re-verify."],
        ["Verification revoked", "Ownership was revoked; start a fresh verification if needed.", "Owner/Admin can Verify ownership again."],
      ] },
      { type: "statusNotice", text: "Team members and clients can view the ownership status but cannot start, check, or revoke verification — that's an owner/admin action." },
      { type: "expectedResult", text: "Once verified, the website becomes eligible for crawling." },
      { type: "relatedLink", articleSlug: "why-ownership-remains-pending", label: "Why ownership remains pending" },
      { type: "relatedLink", articleSlug: "protecting-the-dns-verification-token", label: "Protecting the DNS verification token" },
      { type: "relatedLink", articleSlug: "starting-and-monitoring-a-crawl", label: "Starting and monitoring a crawl" },
    ],
    category: "domain-ownership",
    contentType: "how_to",
    audienceRoles: ["owner", "admin"],
    level: "beginner",
    productArea: "ownership",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 4,
    tags: ["ownership", "dns", "verify"],
    searchAliases: ["verify website", "verify my website", "verify domain", "dns txt", "prove ownership", "verfy domain"],
    relatedArticleIds: ["why-ownership-remains-pending", "protecting-the-dns-verification-token", "starting-and-monitoring-a-crawl"],
    relevantRoutes: ["/seo/websites"],
    contextualStates: ["ownership:unverified", "ownership:pending", "ownership:verified", "ownership:failed", "ownership:revoked"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "why-ownership-remains-pending",
    slug: "why-ownership-remains-pending",
    title: "Why ownership remains pending",
    summary: "What \"pending\" actually means and why it's expected, not a failure.",
    body: [
      { type: "paragraph", text: "There are three separate things worth telling apart when your ownership status stays \"pending\":" },
      { type: "list", items: [
        "UI action accepted — your \"Verify ownership\" or \"Check again\" click was recorded.",
        "Worker path executed — a background process actually performed a real DNS lookup.",
        "Domain actually verified — the status flips to \"verified\" only after a real DNS match.",
      ] },
      { type: "statusNotice", text: "In this build, the background checker is not continuously running. Adding your DNS record and clicking \"Check again\" records your intent, but a real DNS check only happens when an operator runs the checker. Staying \"pending\" after adding the record is expected here." },
      { type: "troubleshootingNote", text: "If you believe your DNS record is correct and it's been a long time, confirm the exact Host and Value match what was shown, then contact support." },
      { type: "relatedLink", articleSlug: "verifying-domain-ownership", label: "Verifying domain ownership" },
    ],
    category: "domain-ownership",
    contentType: "faq",
    audienceRoles: ["owner", "admin"],
    level: "beginner",
    productArea: "ownership",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 2,
    tags: ["ownership", "pending", "dns"],
    searchAliases: ["still pending", "ownership pending", "dns not verifying", "domain pending"],
    relatedArticleIds: ["verifying-domain-ownership", "why-a-crawl-may-remain-queued"],
    relevantRoutes: ["/seo/websites"],
    contextualStates: ["ownership:pending"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "protecting-the-dns-verification-token",
    slug: "protecting-the-dns-verification-token",
    title: "Protecting your DNS verification token",
    summary: "Why the DNS TXT value is a secret, and what to do (and never do) with it.",
    body: [
      { type: "warning", text: "The DNS TXT Value shown during ownership verification is a security-sensitive value for your website. It is safe to place in your own DNS zone, but never paste it into a support chat, email, or public screenshot." },
      { type: "paragraph", text: "Support will never ask you to share this value. If someone asks you for it outside of your own DNS management console, do not provide it." },
      { type: "relatedLink", articleSlug: "verifying-domain-ownership", label: "Verifying domain ownership" },
      { type: "relatedLink", articleSlug: "contacting-support-safely", label: "Contacting support safely" },
    ],
    category: "domain-ownership",
    contentType: "faq",
    audienceRoles: ["owner", "admin"],
    level: "beginner",
    productArea: "ownership",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 1,
    tags: ["security", "dns", "token"],
    searchAliases: ["is the token secret", "dns token safety", "challenge value security"],
    relatedArticleIds: ["verifying-domain-ownership", "contacting-support-safely"],
    relevantRoutes: ["/seo/websites"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
];
