import type { HelpArticle } from "../types";

export const SETUP_ARTICLES: HelpArticle[] = [
  {
    id: "adding-a-website",
    slug: "adding-a-website",
    title: "Adding a website",
    summary: "How to add a website to your workspace so you can start working on its SEO.",
    body: [
      { type: "paragraph", text: "Website owners, admins, and team members can add a new website from the Websites page." },
      { type: "steps", items: [
        "Go to the Websites page.",
        "Enter the Website URL (e.g. https://www.example.com).",
        "Enter a Website name (a label for you, e.g. \"Acme Plumbing - Main Site\").",
        "Enter the Business name.",
        "Choose a Website type.",
        "Save.",
      ] },
      { type: "warning", text: "Website URL, website name, and business name are all required." },
      { type: "expectedResult", text: "The new website appears in your list and can be set as the active website." },
      { type: "troubleshootingNote", text: "If the \"Add website\" action is unavailable, your role may not permit it — clients cannot add websites. Ask an owner, admin, or team member." },
      { type: "relatedLink", articleSlug: "completing-business-onboarding", label: "Completing business onboarding" },
      { type: "relatedLink", articleSlug: "verifying-domain-ownership", label: "Verifying domain ownership" },
    ],
    category: "set-up-digibility-seo",
    contentType: "how_to",
    audienceRoles: ["owner", "admin", "team_member"],
    level: "beginner",
    productArea: "websites",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 2,
    tags: ["add website", "new website", "setup"],
    searchAliases: ["add site", "create website", "new site"],
    relatedArticleIds: ["completing-business-onboarding", "verifying-domain-ownership"],
    relevantRoutes: ["/seo/websites"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "completing-business-onboarding",
    slug: "completing-business-onboarding",
    title: "Completing business onboarding",
    summary: "How to fill in your business profile and why it matters.",
    body: [
      { type: "paragraph", text: "The business onboarding profile stores context about your business: services/products, target audience, main SEO goal, target locations, competitors, proof/trust signals, important pages, preferred content tone, whether the industry is sensitive, and any additional notes." },
      { type: "steps", items: [
        "Go to Business Onboarding for your active website.",
        "Fill in each field as completely as you can.",
        "Save.",
      ] },
      { type: "callout", text: "This profile is stored and surfaced as context in several modules. Treat it today as a stored profile rather than an automation input — it does not yet automatically rewrite audits, keywords, or AI-generated content." },
      { type: "troubleshootingNote", text: "Clients can view onboarding but cannot edit it. Ask an owner, admin, or team member to make changes." },
      { type: "relatedLink", articleSlug: "adding-a-website", label: "Adding a website" },
    ],
    category: "set-up-digibility-seo",
    contentType: "how_to",
    audienceRoles: ["owner", "admin", "team_member"],
    level: "beginner",
    productArea: "onboarding",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["onboarding", "business profile", "setup"],
    searchAliases: ["business profile", "fill onboarding", "setup profile"],
    relatedArticleIds: ["adding-a-website"],
    relevantRoutes: ["/seo/onboarding"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
];
