import type { HelpArticle } from "../types";

export const START_HERE_ARTICLES: HelpArticle[] = [
  {
    id: "getting-started-with-digibility-seo",
    slug: "getting-started-with-digibility-seo",
    title: "Getting started with Digibility SEO",
    summary:
      "What Digibility SEO Intelligence is, who it's for, and what to expect in your first day, week, and month.",
    body: [
      { type: "paragraph", text: "Digibility SEO Intelligence is a website-centric SEO execution workspace. Every audit, page, recommendation, and piece of content is attached to a specific website, so your team always knows exactly what work applies to which site." },
      { type: "heading", id: "who-its-for", text: "Who it's for" },
      { type: "paragraph", text: "Founders and businesses running their own SEO, agencies managing multiple client websites, team members executing work, and clients who need visibility and light participation." },
      { type: "heading", id: "first-day", text: "Your first day" },
      { type: "steps", items: [
        "Sign in with your Digibility account.",
        "Add or select a website.",
        "Complete the business onboarding profile.",
        "Start verifying domain ownership.",
      ] },
      { type: "heading", id: "finding-your-way-around", text: "Finding your way around" },
      { type: "paragraph", text: "The left sidebar groups every page under one expandable SEO section, so it doesn't show a long flat list. Expand SEO, then expand the group you need — for example Setup, Research & Strategy, or Audit & Optimization — to see its pages. SEO Dashboard is always the first link once SEO is expanded, above every group." },
      { type: "heading", id: "first-week", text: "Your first week" },
      { type: "paragraph", text: "Review your audit, page inventory, and page performance once available. Walk through the approval queue and explore the other modules." },
      { type: "heading", id: "first-month", text: "Your first month" },
      { type: "paragraph", text: "Establish a weekly review rhythm and start interpreting reports as your data builds up." },
      { type: "statusNotice", text: "This build is a TEST/preview version of Digibility SEO. Some data you see is seeded demo content, not live analytics. Look for status labels like \"Preview\" or \"Demo data\" throughout the app." },
      { type: "relatedLink", articleSlug: "preview-data-versus-live-data", label: "Is this data real?" },
      { type: "relatedLink", articleSlug: "signing-in-and-access-states", label: "Signing in and access states" },
    ],
    category: "start-here",
    contentType: "quick_start",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "orientation",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["getting started", "orientation", "onboarding"],
    searchAliases: ["what is digibility seo", "where do I start", "get started", "begin", "visibility dashboard", "seo dashboard", "where is the dashboard"],
    relatedArticleIds: ["preview-data-versus-live-data", "signing-in-and-access-states", "adding-a-website"],
    relevantRoutes: ["/seo/dashboard"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "signing-in-and-access-states",
    slug: "signing-in-and-access-states",
    title: "Signing in and understanding access states",
    summary: "How to sign in, what to do if you're redirected, and what each access state means.",
    body: [
      { type: "paragraph", text: "Sign in at the Digibility SEO login page with your existing Digibility account email and password." },
      { type: "heading", id: "invalid-login", text: "Invalid email or password" },
      { type: "paragraph", text: "If you see \"Invalid email or password. Please try again,\" re-enter your credentials. If you've forgotten your password, use your organization's normal Digibility account recovery process." },
      { type: "heading", id: "redirected-to-login", text: "Why was I redirected to sign in?" },
      { type: "paragraph", text: "You tried to open a page that requires an active session. Once you sign in, you're returned to the page you originally requested." },
      { type: "heading", id: "access-required", text: "\"Access required\"" },
      { type: "paragraph", text: "This means your account doesn't currently have SEO module access. Ask a workspace owner or admin to grant it." },
      { type: "expectedResult", text: "After a valid sign-in, you land on the SEO dashboard (or the page you originally tried to reach)." },
      { type: "escalationNote", text: "If sign-in keeps failing after a password reset, contact support with your account email and the exact error message — never your password." },
      { type: "relatedLink", articleSlug: "seo-access-and-entitlements", label: "SEO access and entitlements" },
    ],
    category: "start-here",
    contentType: "how_to",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "auth",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["login", "sign in", "access"],
    searchAliases: ["how do I log in", "why am I redirected", "invalid login", "access denied"],
    relatedArticleIds: ["seo-access-and-entitlements", "getting-started-with-digibility-seo"],
    relevantRoutes: ["/seo/login"],
    contextualStates: ["access:anonymous", "access:resolver-error"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "seo-access-and-entitlements",
    slug: "seo-access-and-entitlements",
    title: "SEO access and entitlements",
    summary: "Why you might see \"Access required\" and how SEO module access works.",
    body: [
      { type: "paragraph", text: "Digibility SEO is a separate module from Digibility Visibility Management. Your account needs SEO module access (an entitlement) before you can use it, even if you already use other parts of Digibility." },
      { type: "definition", term: "Entitlement", text: "A flag on your account that grants access to the SEO module. It is separate from your workspace role." },
      { type: "troubleshootingNote", text: "If you see an access-required screen, ask a workspace owner or admin to grant SEO access, or contact support if you believe this is an error." },
      { type: "relatedLink", articleSlug: "roles-and-permissions", label: "Roles and permissions" },
    ],
    category: "start-here",
    contentType: "faq",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "auth",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 2,
    tags: ["access", "entitlement", "module access"],
    searchAliases: ["why access required", "no seo access", "module access"],
    relatedArticleIds: ["signing-in-and-access-states", "roles-and-permissions"],
    relevantRoutes: [],
    contextualStates: ["access:no-module-access"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "workspaces-and-the-active-website",
    slug: "workspaces-and-the-active-website",
    title: "Workspaces and the active website",
    summary: "Why data is always scoped to one selected website, and how to avoid reading the wrong site's numbers.",
    body: [
      { type: "paragraph", text: "Everything in Digibility SEO is scoped to the currently active website inside your workspace. Switching the active website changes what every module shows." },
      { type: "warning", text: "All data on a website-scoped screen belongs to the currently selected website. Always confirm the website name before acting on what you see." },
      { type: "heading", id: "wrong-data", text: "\"This data looks wrong\"" },
      { type: "paragraph", text: "The most common cause is an unintended active-website switch. Check the website name shown on the page, switch back if needed, and refresh." },
      { type: "relatedLink", articleSlug: "adding-a-website", label: "Adding a website" },
    ],
    category: "start-here",
    contentType: "concept",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "navigation",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["workspace", "active website", "navigation"],
    searchAliases: ["switch website", "wrong website data", "wrong site data", "change website", "active site"],
    relatedArticleIds: ["adding-a-website", "getting-started-with-digibility-seo"],
    relevantRoutes: [],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
];
