import type { HelpArticle } from "../types";

export const WORKFLOW_ARTICLES: HelpArticle[] = [
  {
    id: "the-approval-workflow",
    slug: "the-approval-workflow",
    title: "The approval workflow",
    summary: "How work moves through submit, approve, and reject, and who can do what.",
    body: [
      { type: "paragraph", text: "Approval items keep a full, append-only history of comments and status changes so nothing is silently lost." },
      { type: "steps", items: [
        "A team member (or owner/admin) submits an item.",
        "An owner or admin reviews it in the Approval Queue.",
        "The owner/admin approves or rejects it, optionally with a comment.",
      ] },
      { type: "statusNotice", text: "Clients can view the approval queue and its history, but cannot submit, approve, or reject." },
      { type: "troubleshootingNote", text: "An invalid transition (for example, approving something already approved) is rejected by the system with an explanatory message." },
      { type: "relatedLink", articleSlug: "roles-and-permissions", label: "Roles and permissions" },
    ],
    category: "recommendations-approvals",
    contentType: "workflow",
    audienceRoles: ["owner", "admin", "team_member", "client"],
    level: "beginner",
    productArea: "approvals",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["approvals", "approve", "reject", "review"],
    searchAliases: ["approve reject", "review", "submit for approval", "sign off"],
    relatedArticleIds: ["roles-and-permissions"],
    relevantRoutes: ["/seo/approvals"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
  {
    id: "roles-and-permissions",
    slug: "roles-and-permissions",
    title: "Roles and permissions",
    summary: "What Owner, Admin, Team Member, and Client can each do in Digibility SEO.",
    body: [
      { type: "paragraph", text: "SEO roles are scoped to your workspace and are enforced on the server, not just hidden in the interface." },
      { type: "table", headers: ["Capability", "Owner", "Admin", "Team Member", "Client"], rows: [
        ["View website-scoped modules", "Yes", "Yes", "Yes", "Yes (read-only)"],
        ["Add/manage websites", "Yes", "Yes", "Yes", "No"],
        ["Verify domain ownership", "Yes", "Yes", "No (read-only)", "No (read-only)"],
        ["Start / cancel a crawl", "Yes", "Yes", "Yes", "No"],
        ["Approve / reject", "Yes", "Yes", "No", "No"],
        ["Submit work", "Yes", "Yes", "Yes", "No"],
      ] },
      { type: "callout", text: "If a control is disabled, look for a tooltip explaining the required role, and ask a workspace owner or admin to help." },
      { type: "relatedLink", articleSlug: "the-approval-workflow", label: "The approval workflow" },
      { type: "relatedLink", articleSlug: "verifying-domain-ownership", label: "Verifying domain ownership" },
    ],
    category: "recommendations-approvals",
    contentType: "role_guide",
    audienceRoles: ["all"],
    level: "beginner",
    productArea: "roles",
    featureStatus: "available_on_test",
    estimatedReadingMinutes: 3,
    tags: ["roles", "permissions", "owner", "admin", "team member", "client"],
    searchAliases: ["who can do what", "permission denied", "permision denied", "cannot approve", "can't approve", "no access"],
    relatedArticleIds: ["the-approval-workflow", "verifying-domain-ownership"],
    relevantRoutes: [],
    contextualStates: ["access:role-denied"],
    priority: "P0",
    lastReviewed: "2026-07-19",
    version: "1",
    published: true,
    visibility: "public",
  },
];
